"""empty message

Revision ID: c0ea9f32c79b
Revises: e414119fec33
Create Date: 2019-06-29 22:55:46.738710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ea9f32c79b'
down_revision = 'e414119fec33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('subtitle', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'subtitle')
    # ### end Alembic commands ###
