"""empty message

Revision ID: e414119fec33
Revises: 6998493b503f
Create Date: 2019-06-29 20:42:59.660343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e414119fec33'
down_revision = '6998493b503f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('catColumn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'catColumn')
    # ### end Alembic commands ###
